version: 2
updates:
  # --- Dépendances Python (requirements.txt) ---
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps(pip)"
    open-pull-requests-limit: 5

  # --- Dockerfile (dans docker/) ---
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps(docker)"

  # --- GitHub Actions (workflows dans .github/) ---
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
    commit-message:
      prefix: "deps(actions)"
